# n=int(input('So tien ban dau: '))
# k=int(input('So thang gui: '))
# T=float(input('Lai xuat/ thang: '))
# m=n*(1+k*T)
# print('Voi so tien ban dau ',n,', sau ',k,' thang gui,',' lai suat ',T,'/ thang',sep='')
# print('Thi so tien nhan duoc cuoi ky là:',m)
n=int(input('So tien ban dau: '))
k=int(input('So thang gui: '))
T=float(input('Lai xuat/ thang: '))
m=n*(1+k*T)
print('Voi so tien ban dau ',n,', sau ',k,' thang gui,',' lai suat ',T,'/ thang',sep='')
print('Thi so tien nhan duoc cuoi ky la:',m)